# Generated by Django 5.0.4 on 2024-04-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='meaning',
            field=models.TextField(default='', max_length=255),
        ),
    ]
